=== sqljiang/conformity/platform/com/neusoft/spring/web/context/spring-context-configuration.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" 
		   targetNamespace="http://www.example.org/spring-context-configuration" 
		   xmlns:tns="http://www.example.org/spring-context-configuration" 
		   elementFormDefault="qualified">
	<xs:element name="packages">
		<xs:annotation>
			<xs:documentation>Root Element</xs:documentation>
		</xs:annotation>
		<xs:complexType>
			<xs:sequence>
				<xs:element name="package" minOccurs="1" maxOccurs="unbounded">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="description" type="xs:string" minOccurs="0" maxOccurs="1"/>
							<xs:element name="files" maxOccurs="1">
								<xs:complexType mixed="true">
									<xs:choice>
										<xs:element name="list" minOccurs="0" maxOccurs="1">
											<xs:complexType>
												<xs:sequence>
													<xs:element name="file" minOccurs="0" maxOccurs="unbounded"/>
												</xs:sequence>
											</xs:complexType>
										</xs:element>
									</xs:choice>
								</xs:complexType>
							</xs:element>
						</xs:sequence>
						<xs:attribute name="name" type="xs:string"/>
					</xs:complexType>
				</xs:element>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
</xs:schema>

=== sqljiang/conformity/WebRoot/WEB-INF/config/ess-application-context.xml
<?xml version="1.0" encoding="UTF-8"?>

<packages xmlns="http://www.example.org/spring-context-configuration"
		  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
		  xsi:schemaLocation="http://www.example.org/spring-context-configuration spring-context-configuration/spring-context-configuration.xsd">
	
	<package name="action">
		<description>Struts action configuration</description>
		<files>
			<list>
				<file>/WEB-INF/config/action/applicationContext-fastView.xml</file>
			</list>
		</files>
	</package>
	
	<package name="cache">
		<description>EhCache configuration </description>
		<files>
			<list>
				<file>/WEB-INF/config/cache/applicationContext-ehcache.xml</file>
			</list>
		</files>
	</package>
	
	<package name="common">
		<description>common configuration</description>
		<files>
			<list>
				<file>/WEB-INF/config/common/applicationContext-base.xml</file>
				<file>/WEB-INF/config/common/applicationContext-db.xml</file>
			</list>
		</files>
	</package>
	
	<package name="dao">
		<description>data access</description>
		<files>
			<list>
				<file>/WEB-INF/config/dao/applicationContext-interface-dao.xml</file>
				<file>/WEB-INF/config/dao/applicationContext-fastView-dao.xml</file>
			</list>
		</files>
	</package>
	
	<package name="jndi">
		<description>JNDI configuration</description>
		<files>
			<list>
				<file>/WEB-INF/config/jndi/applicationContext-jndi.xml</file>
			</list>
		</files>
	</package>
	
	<package>
		<description>mina configuration</description>
		<files>
			<list>
				<file>/WEB-INF/config/mina/applicationContext-mina.xml</file>
			</list>
		</files>
	</package>
	
	<package name="quartz">
		<description>quartz configuration</description>
		<files>
			<list>
				<file>/WEB-INF/config/quartz/applicationContext-quartz.xml</file>
			</list>
		</files>
	</package>
	<!-- 
	<package name="security">
		<description>spring security</description>
		<files>
			<list>
				<file>/WEB-INF/config/security/applicationContext-security.xml</file>
				<file>/WEB-INF/config/security/applicationContext-security-config.xml</file>
				<file>/WEB-INF/config/security/applicationContext-security-persistent.xml</file>
			</list>
		</files>
	</package>
	-->
	<package name="server">
		<description>server layout</description>
		<files>
			<list>
				<file>/WEB-INF/config/server/applicationContext-fastView-server.xml</file>
				<file>/WEB-INF/config/server/applicationContext-interface-server.xml</file>
			</list>
		</files>
	</package>
	
	<package>
		<description>Web server configuration</description>
		<files>
			<list>
				<file>/WEB-INF/config/services/applicationContext-ws.xml</file>
			</list>
		</files>
	</package>
	
</packages>
